name: Morning Exercise

on:
  schedule:
    - cron: '48 22 * * *'
  workflow_dispatch:

jobs:
  morning-exercise:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout codes
        uses: actions/checkout@v3
      - name: Setup Python
        uses: actions/setup-python@v3
        with:
          python-version: '3.10'
      - name: Prepare environment
        run: pip install -r requirements.txt
      - name: Run app
        run: python main.py -r 28 -d 1200 -t 420 -q
        env:
          USER_ID: ${{ secrets.USER_ID }}
          FUDAN_SPORT_TOKEN: ${{ secrets.FUDAN_SPORT_TOKEN }}
          PLATFORM_OS: ${{ secrets.PLATFORM_OS }}
          PLATFORM_DEVICE: ${{ secrets.PLATFORM_DEVICE }}
